import { Restaurant } from '@/types'

export const RESTAURANTS: Restaurant[] = [
  // ── NYC (20) ──────────────────────────────────────────────────────────────
  {
    id: 'eleven-madison-park',
    name: 'Eleven Madison Park',
    city: 'New York',
    country: 'USA',
    cuisine: 'Contemporary American',
    michelinStars: 3,
    bookingPlatform: 'resy',
    typicalWait: '4–6 months',
    priceRange: '$$$$',
    description: 'Daniel Humm\'s plant-based temple in a landmark Art Deco dining room. Three Michelin stars and a perennial World\'s 50 Best fixture.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'le-bernardin',
    name: 'Le Bernardin',
    city: 'New York',
    country: 'USA',
    cuisine: 'French Seafood',
    michelinStars: 3,
    bookingPlatform: 'resy',
    typicalWait: '2–4 months',
    priceRange: '$$$$',
    description: 'Eric Ripert\'s legendary seafood institution — three Michelin stars for over two decades. The benchmark for French technique in New York.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'masa',
    name: 'Masa',
    city: 'New York',
    country: 'USA',
    cuisine: 'Japanese Omakase',
    michelinStars: 3,
    bookingPlatform: 'phone',
    typicalWait: '3–5 months',
    priceRange: '$$$$',
    description: 'The most expensive restaurant in the US. Masa Takayama\'s counter seats just 26 — an intimate omakase of flown-in Japanese fish and the finest wagyu.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'per-se',
    name: 'Per Se',
    city: 'New York',
    country: 'USA',
    cuisine: 'Contemporary French',
    michelinStars: 3,
    bookingPlatform: 'tock',
    typicalWait: '2–3 months',
    priceRange: '$$$$',
    description: 'Thomas Keller\'s New York counterpart to The French Laundry — nine-course tasting menus with views over Central Park.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'chefs-table-brooklyn-fare',
    name: "Chef's Table at Brooklyn Fare",
    city: 'New York',
    country: 'USA',
    cuisine: 'French-Japanese',
    michelinStars: 3,
    bookingPlatform: 'tock',
    typicalWait: '4–6 months',
    priceRange: '$$$$',
    description: 'César Ramirez\'s intimate 18-seat counter where French technique meets Japanese precision. One of the hardest bookings in the city.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'atomix',
    name: 'Atomix',
    city: 'New York',
    country: 'USA',
    cuisine: 'Korean Contemporary',
    michelinStars: 2,
    bookingPlatform: 'tock',
    typicalWait: '3–5 months',
    priceRange: '$$$$',
    description: 'Junghyun Park\'s modern Korean tasting menu, ranked in the World\'s 50 Best. A beautifully curated experience of card-based storytelling and exceptional flavour.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'jungsik',
    name: 'Jungsik',
    city: 'New York',
    country: 'USA',
    cuisine: 'Korean Fine Dining',
    michelinStars: 2,
    bookingPlatform: 'resy',
    typicalWait: '1–2 months',
    priceRange: '$$$',
    description: 'Chef Jungsik Yim\'s flagship — modern Korean cuisine elevated to fine dining with a global ingredient philosophy and impeccable execution.',
    availabilityStatus: 'limited',
  },
  {
    id: 'odo',
    name: 'Odo',
    city: 'New York',
    country: 'USA',
    cuisine: 'Japanese Kaiseki',
    michelinStars: 1,
    bookingPlatform: 'tock',
    typicalWait: '2–3 months',
    priceRange: '$$$',
    description: 'Hiroki Odo\'s kaiseki counter brings refined Japanese multi-course cuisine to Flatiron. One Michelin star and a devoted following.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'chefs-counter-noda',
    name: "The Chef's Counter at Noda",
    city: 'New York',
    country: 'USA',
    cuisine: 'Japanese Sushi',
    michelinStars: 1,
    bookingPlatform: 'tock',
    typicalWait: '3–4 months',
    priceRange: '$$$$',
    description: 'A 10-seat omakase counter in Midtown where chef Takashi Abe crafts a deeply seasonal sushi experience rooted in Edomae tradition.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'don-angie',
    name: 'Don Angie',
    city: 'New York',
    country: 'USA',
    cuisine: 'Italian-American',
    michelinStars: 0,
    bookingPlatform: 'resy',
    typicalWait: '6–8 weeks',
    priceRange: '$$$',
    description: 'Scott Tacinelli and Angie Rito\'s West Village trattoria — impossible to book, worth every attempt. The pinwheel lasagne alone is legendary.',
    availabilityStatus: 'unavailable',
  },
  {
    id: '4-charles-prime-rib',
    name: '4 Charles Prime Rib',
    city: 'New York',
    country: 'USA',
    cuisine: 'American Steakhouse',
    michelinStars: 0,
    bookingPlatform: 'resy',
    typicalWait: '4–6 weeks',
    priceRange: '$$$',
    description: 'A tucked-away West Village speakeasy that opens reservations 60 days out — and fills them instantly. Flawless prime rib in an intimate setting.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'carbone',
    name: 'Carbone',
    city: 'New York',
    country: 'USA',
    cuisine: 'Italian-American',
    michelinStars: 0,
    bookingPlatform: 'resy',
    typicalWait: '6–10 weeks',
    priceRange: '$$$',
    description: 'The downtown institution that\'s become a cultural landmark. Rigatoni vodka, tableside caesar, and a room full of downtown energy.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'i-sodi',
    name: 'I Sodi',
    city: 'New York',
    country: 'USA',
    cuisine: 'Tuscan',
    michelinStars: 0,
    bookingPlatform: 'phone',
    typicalWait: '4–6 weeks',
    priceRange: '$$$',
    description: 'Rita Sodi\'s intimate Florentine trattoria in the West Village. Accepts reservations by phone only — a deliberate barrier that makes each table feel earned.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'via-carota',
    name: 'Via Carota',
    city: 'New York',
    country: 'USA',
    cuisine: 'Italian',
    michelinStars: 0,
    bookingPlatform: 'resy',
    typicalWait: '3–5 weeks',
    priceRange: '$$',
    description: 'Jody Williams and Rita Sodi\'s all-day Italian in the West Village. The insalata verde is world-famous. Walk-ins are your best bet.',
    availabilityStatus: 'limited',
  },
  {
    id: 'lartusi',
    name: "L'Artusi",
    city: 'New York',
    country: 'USA',
    cuisine: 'Italian',
    michelinStars: 0,
    bookingPlatform: 'resy',
    typicalWait: '3–4 weeks',
    priceRange: '$$$',
    description: 'The West Village Italian that\'s been quietly excellent for years. Consistently full, consistently delicious — pasta lovers\' paradise.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'tatiana',
    name: 'Tatiana',
    city: 'New York',
    country: 'USA',
    cuisine: 'New American',
    michelinStars: 1,
    bookingPlatform: 'resy',
    typicalWait: '2–4 months',
    priceRange: '$$$',
    description: 'Kwame Onwuachi\'s Lincoln Center restaurant — a celebration of the African diaspora through modern American cuisine. One Michelin star.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'torrisi',
    name: 'Torrisi',
    city: 'New York',
    country: 'USA',
    cuisine: 'Italian-American',
    michelinStars: 0,
    bookingPlatform: 'resy',
    typicalWait: '6–10 weeks',
    priceRange: '$$$',
    description: 'Rich Torrisi\'s tasting-menu-only Italian-American in Nolita. One of the most competitive bookings in New York — opens at midnight and fills in minutes.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'le-pavillon',
    name: 'Le Pavillon',
    city: 'New York',
    country: 'USA',
    cuisine: 'Contemporary French',
    michelinStars: 1,
    bookingPlatform: 'resy',
    typicalWait: '4–6 weeks',
    priceRange: '$$$',
    description: 'Daniel Boulud\'s plant-forward French restaurant in One Vanderbilt — elegant, seasonal, and understated in the best way.',
    availabilityStatus: 'limited',
  },
  {
    id: 'daniel',
    name: 'Daniel',
    city: 'New York',
    country: 'USA',
    cuisine: 'Contemporary French',
    michelinStars: 2,
    bookingPlatform: 'resy',
    typicalWait: '3–6 weeks',
    priceRange: '$$$$',
    description: 'Daniel Boulud\'s flagship on the Upper East Side — a grand two-Michelin-star room that balances classical French cooking with modern sensibility.',
    availabilityStatus: 'limited',
  },
  {
    id: 'the-four-horsemen',
    name: 'The Four Horsemen',
    city: 'New York',
    country: 'USA',
    cuisine: 'New American',
    michelinStars: 0,
    bookingPlatform: 'resy',
    typicalWait: '4–6 weeks',
    priceRange: '$$$',
    description: 'James Murphy\'s Michelin-Bib Gourmand wine bar in Williamsburg — natural wines, thoughtful small plates, and a deeply cool atmosphere.',
    availabilityStatus: 'unavailable',
  },

  // ── London (15) ──────────────────────────────────────────────────────────
  {
    id: 'the-ledbury',
    name: 'The Ledbury',
    city: 'London',
    country: 'UK',
    cuisine: 'Contemporary European',
    michelinStars: 3,
    bookingPlatform: 'opentable',
    typicalWait: '3–6 months',
    priceRange: '$$$$',
    description: 'Brett Graham\'s Notting Hill landmark — three Michelin stars and arguably the best restaurant in London. A study in pure craft and seasonal produce.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'sketch-lecture-room',
    name: 'Sketch (Lecture Room)',
    city: 'London',
    country: 'UK',
    cuisine: 'French',
    michelinStars: 2,
    bookingPlatform: 'direct',
    typicalWait: '2–3 months',
    priceRange: '$$$$',
    description: 'Pierre Gagnaire\'s opulent Mayfair dining room — two Michelin stars, extraordinary French cuisine, and one of the most memorable rooms in the world.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'core-by-clare-smyth',
    name: 'Core by Clare Smyth',
    city: 'London',
    country: 'UK',
    cuisine: 'Contemporary British',
    michelinStars: 3,
    bookingPlatform: 'tock',
    typicalWait: '3–5 months',
    priceRange: '$$$$',
    description: 'Clare Smyth\'s Notting Hill restaurant — three Michelin stars and a portfolio of dishes celebrating British produce at its absolute finest.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'ikoyi',
    name: 'Ikoyi',
    city: 'London',
    country: 'UK',
    cuisine: 'West African Contemporary',
    michelinStars: 2,
    bookingPlatform: 'sevenrooms',
    typicalWait: '2–4 months',
    priceRange: '$$$$',
    description: 'Jeremy Chan and Iré Hassan-Odukale\'s boundary-defining restaurant — West African ingredients and flavours elevated through a fine dining lens. World\'s 50 Best.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'da-terra',
    name: 'Da Terra',
    city: 'London',
    country: 'UK',
    cuisine: 'Contemporary European',
    michelinStars: 2,
    bookingPlatform: 'sevenrooms',
    typicalWait: '2–3 months',
    priceRange: '$$$',
    description: 'Rafael Cagali\'s intimate Bethnal Green restaurant — two Michelin stars for a deeply personal tasting menu rooted in his Italian-Brazilian heritage.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'kitchen-table',
    name: 'Kitchen Table',
    city: 'London',
    country: 'UK',
    cuisine: 'Contemporary European',
    michelinStars: 2,
    bookingPlatform: 'resy',
    typicalWait: '3–5 months',
    priceRange: '$$$$',
    description: 'James Knappett\'s 20-seat counter in Fitzrovia — two Michelin stars for an immersive, kitchen-view tasting menu built around the best British produce.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'a-wong',
    name: 'A. Wong',
    city: 'London',
    country: 'UK',
    cuisine: 'Chinese Contemporary',
    michelinStars: 2,
    bookingPlatform: 'sevenrooms',
    typicalWait: '2–4 months',
    priceRange: '$$$',
    description: 'Andrew Wong\'s Westminster restaurant — two Michelin stars for a boundary-pushing journey through Chinese culinary history. First Chinese restaurant in Europe to achieve two stars.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'brat',
    name: 'Brat',
    city: 'London',
    country: 'UK',
    cuisine: 'Contemporary British',
    michelinStars: 1,
    bookingPlatform: 'direct',
    typicalWait: '6–8 weeks',
    priceRange: '$$$',
    description: 'Tomos Parry\'s Basque-inspired wood-fire restaurant in Shoreditch — one Michelin star and a committed following for its whole-roasted turbot and ember-charred everything.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'the-clove-club',
    name: 'The Clove Club',
    city: 'London',
    country: 'UK',
    cuisine: 'Contemporary British',
    michelinStars: 1,
    bookingPlatform: 'opentable',
    typicalWait: '6–10 weeks',
    priceRange: '$$$',
    description: 'Isaac McHale\'s Shoreditch restaurant — one Michelin star and a long run in the World\'s 50 Best for fiercely seasonal British cooking.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'lyles',
    name: "Lyle's",
    city: 'London',
    country: 'UK',
    cuisine: 'Contemporary British',
    michelinStars: 1,
    bookingPlatform: 'direct',
    typicalWait: '4–6 weeks',
    priceRange: '$$$',
    description: 'James Lowe\'s Shoreditch institution — one Michelin star for stripped-back, produce-led British cuisine that helped define the city\'s modern restaurant movement.',
    availabilityStatus: 'limited',
  },
  {
    id: 'st-john',
    name: 'St. John',
    city: 'London',
    country: 'UK',
    cuisine: 'British',
    michelinStars: 1,
    bookingPlatform: 'opentable',
    typicalWait: '3–4 weeks',
    priceRange: '$$',
    description: 'Fergus Henderson\'s Smithfield icon — the restaurant that put nose-to-tail eating on the map. One Michelin star and a permanent place in culinary history.',
    availabilityStatus: 'limited',
  },
  {
    id: 'rochelle-canteen',
    name: 'Rochelle Canteen',
    city: 'London',
    country: 'UK',
    cuisine: 'British',
    michelinStars: 0,
    bookingPlatform: 'direct',
    typicalWait: '2–3 weeks',
    priceRange: '$$',
    description: 'Margot Henderson\'s legendary canteen in a converted bike shed — deceptively simple British cooking that\'s quietly become one of the most beloved restaurants in London.',
    availabilityStatus: 'limited',
  },
  {
    id: 'river-cafe',
    name: 'River Café',
    city: 'London',
    country: 'UK',
    cuisine: 'Italian',
    michelinStars: 1,
    bookingPlatform: 'phone',
    typicalWait: '4–6 weeks',
    priceRange: '$$$$',
    description: 'Ruth Rogers\' Thames-side Italian institution — one Michelin star for ingredients-first Italian cooking that\'s inspired a generation of London chefs.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'noble-rot-soho',
    name: 'Noble Rot Soho',
    city: 'London',
    country: 'UK',
    cuisine: 'Contemporary European',
    michelinStars: 0,
    bookingPlatform: 'sevenrooms',
    typicalWait: '2–4 weeks',
    priceRange: '$$$',
    description: 'The Soho outpost of the beloved wine bar and restaurant — an exceptional natural wine list matched by French-leaning cooking that punches above its weight.',
    availabilityStatus: 'limited',
  },
  {
    id: 'brat-shoreditch-roof',
    name: 'Brat x Climpson\'s Arch',
    city: 'London',
    country: 'UK',
    cuisine: 'Contemporary British',
    michelinStars: 1,
    bookingPlatform: 'direct',
    typicalWait: '8–10 weeks',
    priceRange: '$$$',
    description: 'Tomos Parry\'s seasonal pop-up extension of Brat — wood-fire cooking under the railway arches in London Fields. Limited dates make this exceptionally hard to book.',
    availabilityStatus: 'unavailable',
  },

  // ── World (15) ───────────────────────────────────────────────────────────
  {
    id: 'noma',
    name: 'Noma',
    city: 'Copenhagen',
    country: 'Denmark',
    cuisine: 'New Nordic',
    michelinStars: 3,
    bookingPlatform: 'tock',
    typicalWait: '6–12 months',
    priceRange: '$$$$',
    description: 'René Redzepi\'s legendary Copenhagen restaurant — four times World\'s Best. Now operating as a food lab and pop-up series, each sitting is a once-in-a-lifetime experience.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'osteria-francescana',
    name: 'Osteria Francescana',
    city: 'Modena',
    country: 'Italy',
    cuisine: 'Italian Contemporary',
    michelinStars: 3,
    bookingPlatform: 'direct',
    typicalWait: '6–12 months',
    priceRange: '$$$$',
    description: 'Massimo Bottura\'s three-Michelin-star restaurant in Modena — three times World\'s Best and home to dishes like Five Ages of Parmigiano Reggiano that changed fine dining forever.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'mirazur',
    name: 'Mirazur',
    city: 'Menton',
    country: 'France',
    cuisine: 'Contemporary Mediterranean',
    michelinStars: 3,
    bookingPlatform: 'direct',
    typicalWait: '6–9 months',
    priceRange: '$$$$',
    description: 'Mauro Colagreco\'s three-Michelin-star restaurant overlooking the Mediterranean — World\'s Best 2019, with a garden that provides much of its extraordinary produce.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'central',
    name: 'Central',
    city: 'Lima',
    country: 'Peru',
    cuisine: 'Peruvian Contemporary',
    michelinStars: 0,
    bookingPlatform: 'direct',
    typicalWait: '4–6 months',
    priceRange: '$$$$',
    description: 'Virgilio Martínez and Pía León\'s World\'s Best 2023 — a vertical journey through Peru\'s ecosystems, from sea level to the Andes, in a single extraordinary tasting menu.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'gaggan',
    name: 'Gaggan',
    city: 'Bangkok',
    country: 'Thailand',
    cuisine: 'Indian Progressive',
    michelinStars: 2,
    bookingPlatform: 'direct',
    typicalWait: '3–5 months',
    priceRange: '$$$$',
    description: 'Gaggan Anand\'s punk Indian tasting menu in Bangkok — emoji-only menus, 25+ courses, and the most exhilarating dining experience in Southeast Asia. Four-time Asia\'s 50 Best.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'den-tokyo',
    name: 'Den',
    city: 'Tokyo',
    country: 'Japan',
    cuisine: 'Japanese Contemporary',
    michelinStars: 2,
    bookingPlatform: 'direct',
    typicalWait: '3–6 months',
    priceRange: '$$$',
    description: 'Zaiyu Hasegawa\'s playful Japanese fine dining in Jimbocho — two Michelin stars and consistent top-10 in Asia\'s 50 Best. Witty, warm, and deeply technically brilliant.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'florilege',
    name: 'Florilège',
    city: 'Tokyo',
    country: 'Japan',
    cuisine: 'French Contemporary',
    michelinStars: 2,
    bookingPlatform: 'direct',
    typicalWait: '3–5 months',
    priceRange: '$$$$',
    description: 'Hiroyasu Kawate\'s counter-format French restaurant in Aoyama — two Michelin stars for plant-forward cooking that bridges French technique and Japanese sensibility.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'narisawa',
    name: 'Narisawa',
    city: 'Tokyo',
    country: 'Japan',
    cuisine: 'Innovative Satoyama',
    michelinStars: 2,
    bookingPlatform: 'direct',
    typicalWait: '3–6 months',
    priceRange: '$$$$',
    description: 'Yoshihiro Narisawa\'s singular restaurant — two Michelin stars for "Innovative Satoyama Cuisine", a philosophy of harmony between humans and the natural world expressed on the plate.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'quintonil',
    name: 'Quintonil',
    city: 'Mexico City',
    country: 'Mexico',
    cuisine: 'Mexican Contemporary',
    michelinStars: 0,
    bookingPlatform: 'tock',
    typicalWait: '2–4 months',
    priceRange: '$$$',
    description: 'Jorge Vallejo\'s modern Mexican in Polanco — a perennial World\'s 50 Best entry for cooking that honours traditional Mexican flavours through an entirely contemporary lens.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'pujol',
    name: 'Pujol',
    city: 'Mexico City',
    country: 'Mexico',
    cuisine: 'Mexican Contemporary',
    michelinStars: 0,
    bookingPlatform: 'tock',
    typicalWait: '2–3 months',
    priceRange: '$$$',
    description: 'Enrique Olvera\'s Mexico City flagship — the restaurant that put modern Mexican cuisine on the world stage. The mole madre, aged 1,000+ days, is the most iconic dish in Latin America.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'geranium',
    name: 'Geranium',
    city: 'Copenhagen',
    country: 'Denmark',
    cuisine: 'New Nordic',
    michelinStars: 3,
    bookingPlatform: 'direct',
    typicalWait: '4–8 months',
    priceRange: '$$$$',
    description: 'Rasmus Kofoed\'s three-Michelin-star restaurant on the 8th floor of Denmark\'s national stadium — World\'s Best 2022 and a visually breathtaking celebration of the Nordic seasons.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'alchemist',
    name: 'Alchemist',
    city: 'Copenhagen',
    country: 'Denmark',
    cuisine: 'Holistic Cuisine',
    michelinStars: 2,
    bookingPlatform: 'direct',
    typicalWait: '6–12 months',
    priceRange: '$$$$',
    description: 'Rasmus Munk\'s 50-course theatrical experience — two Michelin stars, a 180° dome projection screen, and dishes that address climate, ethics, and health. Nothing else like it.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'frantzen',
    name: 'Frantzén',
    city: 'Stockholm',
    country: 'Sweden',
    cuisine: 'Contemporary Nordic-Asian',
    michelinStars: 3,
    bookingPlatform: 'direct',
    typicalWait: '6–10 months',
    priceRange: '$$$$',
    description: 'Björn Frantzén\'s three-Michelin-star townhouse — 12 seats over three floors, a menu blending Nordic produce with Japanese technique, and among Europe\'s hardest reservations.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'diverxo',
    name: 'DiverXO',
    city: 'Madrid',
    country: 'Spain',
    cuisine: 'Avant-Garde',
    michelinStars: 3,
    bookingPlatform: 'direct',
    typicalWait: '6–12 months',
    priceRange: '$$$$',
    description: 'David Muñoz\'s three-Michelin-star spectacle in Madrid — surrealist décor, 30-course menus, edible sculptures, and a booking system that opens months in advance and fills in hours.',
    availabilityStatus: 'unavailable',
  },
  {
    id: 'asador-etxebarri',
    name: 'Asador Etxebarri',
    city: 'Atxondo',
    country: 'Spain',
    cuisine: 'Basque Grill',
    michelinStars: 1,
    bookingPlatform: 'phone',
    typicalWait: '4–6 months',
    priceRange: '$$$',
    description: 'Victor Arguinzoniz\'s wood-fire sanctuary in the Basque mountains — one Michelin star and consistently top-3 in the World\'s 50 Best. The greatest grill restaurant on earth.',
    availabilityStatus: 'unavailable',
  },
]

export function getRestaurantById(id: string): Restaurant | undefined {
  return RESTAURANTS.find(r => r.id === id)
}

export const CITIES = [
  'New York',
  'London',
  'Copenhagen',
  'Tokyo',
  'Mexico City',
  'Modena',
  'Menton',
  'Lima',
  'Bangkok',
  'Stockholm',
  'Madrid',
  'Atxondo',
] as const

export const BOOKING_PLATFORMS = [
  { value: 'resy', label: 'Resy' },
  { value: 'tock', label: 'Tock' },
  { value: 'sevenrooms', label: 'SevenRooms' },
  { value: 'opentable', label: 'OpenTable' },
  { value: 'thefork', label: 'TheFork' },
  { value: 'direct', label: 'Direct' },
  { value: 'phone', label: 'Phone' },
] as const
